# Generated by Django 5.1 on 2024-08-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('basicPercentage', models.IntegerField(default=50)),
                ('basic', models.IntegerField()),
                ('nonBasicsPercentage', models.IntegerField(default=25)),
                ('nonBasics', models.IntegerField()),
                ('savingsAndInvestmentPercentage', models.IntegerField(default=25)),
                ('savingsAndInvestment', models.IntegerField()),
            ],
        ),
    ]
